FROM postgres:latest

# Install locales and generate-locales
RUN apt-get update && apt-get install -y locales && apt-get install -y locales-all

# Generate the de_DE.UTF-8 locale
RUN locale-gen de_DE.UTF-8

# Set the default locale
ENV LANG de_DE.UTF-8
ENV LANGUAGE de_DE:de
ENV LC_ALL de_DE.UTF-8

