CREATE TABLE IF NOT EXISTS `zsv_bewerber` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DSGVO` tinyint(1) DEFAULT 0,
  `SCHULJAHR` int(11) DEFAULT NULL,
  `Anmelderunde` tinyint(1) DEFAULT 1,
  `Anmeldungstyp` varchar(16) DEFAULT NULL,
  `Kontaktmailadresse` varchar(64) DEFAULT NULL,
  `Code` varchar(64) DEFAULT NULL,
  `Phase` tinyint(1) DEFAULT NULL,
  `Schuelerkennzahl` bigint(14) unsigned DEFAULT NULL,
  `existiert` tinyint(1) DEFAULT 0,
  `Anmeldenummer` bigint(20) DEFAULT NULL,
  `Anrede` varchar(8) DEFAULT NULL,
  `Titelvor` varchar(64) DEFAULT NULL,
  `Titelnach` varchar(64) DEFAULT NULL,
  `Nachname` varchar(32) DEFAULT NULL,
  `Vorname` varchar(32) DEFAULT NULL,
  `Vornamen` varchar(32) DEFAULT NULL,
  `Geburtsdatum` date DEFAULT NULL,
  `Geschlecht` char(1) DEFAULT NULL,
  `SozialversicherungAUT` tinyint(1) DEFAULT 1,
  `SOZIALVERSICHERUNGSTRAEGER` int(11) DEFAULT NULL,
  `Sozialversicherungsnummer` varchar(8) DEFAULT NULL,
  `SozialversicherungsGebDat` varchar(8) DEFAULT NULL,
  `BILDOKNummer` varchar(16) DEFAULT NULL,
  `Geburtsort` varchar(32) DEFAULT NULL,
  `GEBURTSLAND` int(11) DEFAULT NULL,
  `STAATSBUERGERSCHAFT` int(11) DEFAULT NULL,
  `ERSTSPRACHE` int(11) DEFAULT NULL,
  `ZWEITSPRACHE` int(11) DEFAULT NULL,
  `RELIGIONSBEKENNTNIS` int(11) DEFAULT NULL,
  `Strasse` varchar(64) DEFAULT NULL,
  `Hausnummer` varchar(32) DEFAULT NULL,
  `Postleitzahl` varchar(8) DEFAULT NULL,
  `Wohnort` varchar(128) DEFAULT NULL,
  `Wohnortkennzahl` varchar(8) DEFAULT NULL,
  `Gemeindekennzahl` varchar(8) DEFAULT NULL,
  `WOHNLAND` int(11) DEFAULT NULL,
  `Laendervorwahl1` varchar(4) DEFAULT NULL,
  `Vorwahl1` varchar(8) DEFAULT NULL,
  `Nummer1` varchar(32) DEFAULT NULL,
  `Laendervorwahl2` varchar(4) DEFAULT NULL,
  `Vorwahl2` varchar(8) DEFAULT NULL,
  `Nummer2` varchar(32) DEFAULT NULL,
  `Mailadresse` varchar(64) DEFAULT NULL,
  `Schulpflicht` tinyint(1) DEFAULT NULL,
  `Asylwerber` tinyint(1) DEFAULT NULL,
  `VERHAELTNISA` int(11) DEFAULT NULL,
  `AnredeA` varchar(8) DEFAULT NULL,
  `TitelvorA` varchar(64) DEFAULT NULL,
  `TitelnachA` varchar(64) DEFAULT NULL,
  `NachnameA` varchar(32) DEFAULT NULL,
  `VornameA` varchar(32) DEFAULT NULL,
  `StrasseA` varchar(64) DEFAULT NULL,
  `HausnummerA` varchar(16) DEFAULT NULL,
  `PostleitzahlA` varchar(8) DEFAULT NULL,
  `WohnortA` varchar(32) DEFAULT NULL,
  `WohnortkennzahlA` varchar(8) DEFAULT NULL,
  `GemeindekennzahlA` varchar(8) DEFAULT NULL,
  `WOHNLANDA` int(11) DEFAULT NULL,
  `LaendervorwahlA1` varchar(4) DEFAULT NULL,
  `VorwahlA1` varchar(8) DEFAULT NULL,
  `NummerA1` varchar(32) DEFAULT NULL,
  `LaendervorwahlA2` varchar(4) DEFAULT NULL,
  `VorwahlA2` varchar(8) DEFAULT NULL,
  `NummerA2` varchar(32) DEFAULT NULL,
  `MailadresseA` varchar(64) DEFAULT NULL,
  `VERHAELTNISB` int(11) DEFAULT NULL,
  `AnredeB` varchar(8) DEFAULT NULL,
  `TitelvorB` varchar(64) DEFAULT NULL,
  `TitelnachB` varchar(64) DEFAULT NULL,
  `NachnameB` varchar(32) DEFAULT NULL,
  `VornameB` varchar(32) DEFAULT NULL,
  `StrasseB` varchar(64) DEFAULT NULL,
  `HausnummerB` varchar(16) DEFAULT NULL,
  `PostleitzahlB` varchar(8) DEFAULT NULL,
  `WohnortB` varchar(32) DEFAULT NULL,
  `WohnortkennzahlB` varchar(8) DEFAULT NULL,
  `GemeindekennzahlB` varchar(8) DEFAULT NULL,
  `WOHNLANDB` int(11) DEFAULT NULL,
  `LaendervorwahlB1` varchar(4) DEFAULT NULL,
  `VorwahlB1` varchar(8) DEFAULT NULL,
  `NummerB1` varchar(32) DEFAULT NULL,
  `LaendervorwahlB2` varchar(4) DEFAULT NULL,
  `VorwahlB2` varchar(8) DEFAULT NULL,
  `NummerB2` varchar(32) DEFAULT NULL,
  `MailadresseB` varchar(64) DEFAULT NULL,
  `Geschwisteranzahl` tinyint(4) DEFAULT 0,
  `Geschwisteranschule` tinyint(4) DEFAULT 0,
  `Geschwisternamen` varchar(256) DEFAULT NULL,
  `Erstwunsch` tinyint(1) DEFAULT 1,
  `Erstwunschschule` varchar(64) DEFAULT NULL,
  `Erstwunschschulkennzahl` varchar(6) DEFAULT NULL,
  `Zweitwunschschule` varchar(64) DEFAULT NULL,
  `Zweitwunschschulkennzahl` varchar(6) DEFAULT NULL,
  `FACHRICHTUNG1` int(11) DEFAULT NULL,
  `FACHRICHTUNG2` int(11) DEFAULT NULL,
  `FACHRICHTUNG3` int(11) DEFAULT NULL,
  `Eignungstestdatum` date DEFAULT NULL,
  `Eignungstest` int(4) DEFAULT NULL,
  `Eignungstestnote` int(4) DEFAULT NULL,
  `LetzteSchulform` varchar(128) DEFAULT NULL,
  `LetzteSchuleZeugnis` tinyint(1) DEFAULT 0,
  `LetzteSchuleNation` char(1) DEFAULT NULL,
  `LetzteSchuleTyp` varchar(128) DEFAULT NULL,
  `LetzteSchule` varchar(256) DEFAULT NULL,
  `LetzteSchulkennzahl` varchar(6) DEFAULT NULL,
  `NotentypM` varchar(24) DEFAULT NULL,
  `M` tinyint(4) DEFAULT NULL,
  `NotentypD` varchar(24) DEFAULT NULL,
  `D` tinyint(4) DEFAULT NULL,
  `NotentypE` varchar(24) DEFAULT NULL,
  `E` tinyint(4) DEFAULT NULL,
  `PH` tinyint(4) DEFAULT NULL,
  `CH` tinyint(4) DEFAULT NULL,
  `GG` tinyint(4) DEFAULT NULL,
  `GS` tinyint(4) DEFAULT NULL,
  `reihen` tinyint(1) DEFAULT 0,
  `Punkte` decimal(6,2) DEFAULT NULL,
  `ZUTEILUNG` int(11) DEFAULT NULL,
  `Zuteilungsstatus` tinyint(4) DEFAULT NULL,
  `KLASSE` int(11) DEFAULT NULL,
  `Anmerkungen` text DEFAULT NULL,
  `registriert` datetime DEFAULT NULL,
  `angemeldet` datetime DEFAULT NULL,
  `abgemeldet` datetime DEFAULT NULL,
  `geloescht` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `ZSV_Bewerber_FK_1` (`FACHRICHTUNG1`),
  KEY `ZSV_Bewerber_FK_2` (`FACHRICHTUNG2`),
  KEY `ZSV_Bewerber_FK_3` (`ZUTEILUNG`),
  KEY `ZSV_Bewerber_FK_4` (`GEBURTSLAND`),
  KEY `ZSV_Bewerber_FK_5` (`WOHNLAND`),
  KEY `ZSV_Bewerber_FK_6` (`WOHNLANDA`),
  KEY `ZSV_Bewerber_FK_7` (`WOHNLANDB`),
  KEY `ZSV_Bewerber_FK_8` (`RELIGIONSBEKENNTNIS`),
  KEY `ZSV_Bewerber_FK_9` (`ERSTSPRACHE`),
  KEY `ZSV_Bewerber_FK_10` (`ZWEITSPRACHE`),
  KEY `ZSV_Bewerber_FK_11` (`STAATSBUERGERSCHAFT`),
  KEY `ZSV_Bewerber_FK_12` (`VERHAELTNISA`),
  KEY `ZSV_Bewerber_FK_13` (`VERHAELTNISB`),
  KEY `ZSV_Bewerber_FK_14` (`SCHULJAHR`),
  KEY `ZSV_Bewerber_FK_15` (`SOZIALVERSICHERUNGSTRAEGER`),
  KEY `ZSV_Bewerber_FK_16` (`FACHRICHTUNG3`),
  KEY `ZSV_Bewerber_FK_17` (`KLASSE`),
  CONSTRAINT `ZSV_Bewerber_FK_1` FOREIGN KEY (`FACHRICHTUNG1`) REFERENCES `zsv_fachrichtungen` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_10` FOREIGN KEY (`ZWEITSPRACHE`) REFERENCES `zsv_sprachen` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_11` FOREIGN KEY (`STAATSBUERGERSCHAFT`) REFERENCES `zsv_staatsbuergerschaften` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_12` FOREIGN KEY (`VERHAELTNISA`) REFERENCES `zsv_verhaeltnisse` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_13` FOREIGN KEY (`VERHAELTNISB`) REFERENCES `zsv_verhaeltnisse` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_14` FOREIGN KEY (`SCHULJAHR`) REFERENCES `zsv_schuljahre` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_15` FOREIGN KEY (`SOZIALVERSICHERUNGSTRAEGER`) REFERENCES `zsv_sozialversicherungstraeger` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_16` FOREIGN KEY (`FACHRICHTUNG3`) REFERENCES `zsv_fachrichtungen` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_17` FOREIGN KEY (`KLASSE`) REFERENCES `zsv_klassen` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_2` FOREIGN KEY (`FACHRICHTUNG2`) REFERENCES `zsv_fachrichtungen` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_3` FOREIGN KEY (`ZUTEILUNG`) REFERENCES `zsv_fachrichtungen` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_4` FOREIGN KEY (`GEBURTSLAND`) REFERENCES `zsv_laender` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_5` FOREIGN KEY (`WOHNLAND`) REFERENCES `zsv_laender` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_6` FOREIGN KEY (`WOHNLANDA`) REFERENCES `zsv_laender` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_7` FOREIGN KEY (`WOHNLANDB`) REFERENCES `zsv_laender` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_8` FOREIGN KEY (`RELIGIONSBEKENNTNIS`) REFERENCES `zsv_religionsbekenntnisse` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ZSV_Bewerber_FK_9` FOREIGN KEY (`ERSTSPRACHE`) REFERENCES `zsv_sprachen` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1192 DEFAULT CHARSET=utf8mb3;